export const ColorPallete = {
    primary: 'var(--primary-color)',
    accent: 'var(--accent-color)',
    dark: 'var(--dark-color)',
    light: 'var(--light-color)',
    success: 'var(--success-color)',
    danger: 'var(--danger-color)',
    info: 'var(--info-color)',
    warning: 'var(--warning-color)',
    darkShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--dark-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--dark-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--dark-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--dark-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--dark-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--dark-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--dark-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--dark-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--dark-color))',
    },
    darkTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--dark-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--dark-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--dark-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--dark-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--dark-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--dark-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--dark-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--dark-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--dark-color))',
    },
    lightShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--light-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--light-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--light-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--light-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--light-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--light-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--light-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--light-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--light-color))',
    },
    lightTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--light-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--light-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--light-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--light-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--light-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--light-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--light-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--light-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--light-color))',
    },
}